development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: rails-template_development
  pool:     5
  username: rails-template
  password:
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: rails-template_test
  pool:     5
  username: rails-template
  password:
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: rails-template_production
  pool:     5
  username: rails-template
  password:
  template: template0
