default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 5
  username: rails-template
  password:
  template: template0

development:
  <<: *default
  database: rails-template_development

test:
  <<: *default
  database: rails-template_test

production:
  <<: *default
  database: rails-template_production
